### ISSUE TITLE
False positive for strings

### ISSUE THREAD

**Issue by ainar-g** [kyoh86/looppointer#14]
This is probably caused by #9.

```go
package main

import "fmt"

var a = []string{
	"123",
	"456",
	"789",
}

func main() {
	var s []string
	for _, e := range a {
		s = append(s, e[:1])
	}

	fmt.Printf("%q", s)
}
```

https://go.dev/play/p/wZlGKu6UYRd

Checking this code with `looppointer` v0.2.0 produces:

```none
main.go:14:17: taking a ref for the slice from loop variable e
```

But there is no error in the code, because strings are immutable slices, so there is no reference to the original value here.

**Comment by kyoh86** [comment]
It is fixed on main branch, and may be released soon (now running action)

**Comment by ainar-g** [comment]
Thank you for the very quick fix!  I'll be able to recheck from `main` later today or tomorrow.

**Comment by ainar-g** [comment]
I confirm that the issue is fixed now, thanks again!
