### ISSUE TITLE
Possible exceptions to the array slicing rule

### ISSUE THREAD

**Issue by ainar-g** [kyoh86/looppointer#15]
I'm not sure if these are in the scope for the tool, but here are some examples of code which slices the array arguments, but not in a buggy way:

```go
arrs := [][3]byte{
	{1, 2, 3},
	{4, 5, 6},
	{7, 8, 9},
}

sl := make([]byte, 3)
hexSl := make([]byte, hex.EncodedLen(3))
for _, arr := range arrs {
	copy(sl, arr[:])          // ← Line A
	hex.Encode(hexSl, arr[:]) // ← Line B
	fmt.Printf("slice: %v\nhex slice: %s\n", sl, hexSl)
}
```

https://go.dev/play/p/XF7Y2oKaKzK

At both Line A and Line B the slicing is safe, because essentially a copy is being made.  But `looppointer` as of v0.2.1 reports both of these as unsafe references.

**Comment by kyoh86** [comment]
YES.
looppinter reports all pointers or slice references for loop variables as issues.
it won't decide whether it is in buggy ways or not.

**Comment by kyoh86** [comment]
:memo: if you wanna know the policy to report from looppointer, see: https://github.com/kyoh86/looppointer#sensing-policy
