### ISSUE TITLE
Make it part of golangci-lint?

### ISSUE THREAD

**Issue by guettli** [kyoh86/looppointer#17]
Why not make this linter part of golangci-lint?

**Comment by kyoh86** [comment]
Search golangci-lint issues why it is, and create new one on there if you are not convinced.

**Comment by guettli** [comment]
I don't understand why they don't want to add looppointer. 

Here is the related issue:  https://github.com/golangci/golangci-lint/issues/1404

**Comment by kyoh86** [comment]
me too. 
I won't contribute to their project because I don't share any of thier indecitive and inconsistent policies.
