### ISSUE TITLE
take sliced arrays into account

### ISSUE THREAD

**Issue by ainar-g** [kyoh86/looppointer#9]
Version: `v0.1.8-0.20210505110901-096fec221b2c`.

Code:

```go
package main

import "fmt"

var a = [][3]int{
	{1, 2, 3},
	{4, 5, 6},
	{7, 8, 9},
}

func main() {
	var s [][]int
	for _, e := range a {
		s = append(s, e[:])
	}

	fmt.Println(s)
}
```

Playground: https://play.golang.org/p/B0RQwWK9-IJ.

Expected:

```
[[1 2 3] [4 5 6] [7 8 9]]
```

Actual:

```
[[7 8 9] [7 8 9] [7 8 9]]
```

Array slicing is an operation that results in taking the address of the value, so `looppointer` should take it into account when reporting taking addresses to loop variables.  In all kinds of loops, including where the array is the map key(!).

Please tell me if I can provide any additional information.

**Comment by kyoh86** [comment]
@ainar-g It is cared in v0.2.0
